---
apiVersion: v1
kind: Pod
metadata:
  name: init-containers
spec:
  contianers:
    - name: init-contianer
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
      initContianers:
        - name: init-api-service
          image: alpine:3
          command: ["sleep", "30s"]
        - name: init-db-service
          image: alpine:3
          command: ["sleep", "10s"]