---
apiVersion: v1
kind: Pod
metadata:
  name: limits-pod
spec:
  contianers:
    - name: limit-container
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: "250m"
          memory: "250mi"
        limits: 
          cpu: "1000m"
          memory: "1000mi"
      