---
apiVersion: v1
kind: Pod
metadata:
  name: init-containers
spec:
  contianers:
    - name: init-contianer
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: "250m"
          memory: "250mi"
    